import {UsersIcon} from '@sanity/icons'
import {defineField, defineType} from 'sanity'

export const provider = defineType({
  name: 'provider',
  title: 'Team member',
  type: 'document',
  icon: UsersIcon,
  groups: [
    {name: 'profile', title: 'Profile', default: true},
    {name: 'content', title: 'Bio & details'},
    {name: 'settings', title: 'Settings'},
  ],
  fields: [
    defineField({
      name: 'firstName',
      title: 'First name',
      type: 'string',
      group: 'profile',
    }),
    defineField({
      name: 'lastName',
      title: 'Last name',
      type: 'string',
      group: 'profile',
    }),
    defineField({
      name: 'name',
      title: 'Display name',
      type: 'string',
      group: 'profile',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      group: 'settings',
      options: {source: 'name'},
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'role',
      title: 'Role',
      type: 'string',
      group: 'profile',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'credentials',
      title: 'Credentials',
      type: 'string',
      group: 'profile',
    }),
    defineField({
      name: 'department',
      title: 'Department',
      type: 'string',
      group: 'profile',
      options: {
        list: [
          'Primary care',
          'Treatment services',
          'Care coordination',
          'Administration',
          'Operations',
          'Community outreach',
        ],
      },
    }),
    defineField({
      name: 'pronouns',
      title: 'Pronouns',
      type: 'string',
      group: 'profile',
    }),
    defineField({
      name: 'image',
      title: 'Headshot',
      type: 'image',
      group: 'profile',
      options: {hotspot: true},
      fields: [
        defineField({
          name: 'alt',
          title: 'Alt text',
          type: 'string',
          description: 'Describe the image for screen readers.',
        }),
      ],
    }),
    defineField({
      name: 'shortBio',
      title: 'Short bio',
      type: 'text',
      rows: 3,
      group: 'content',
      description: 'Brief summary used on team cards.',
    }),
    defineField({
      name: 'bio',
      title: 'Full bio',
      type: 'text',
      rows: 6,
      group: 'content',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'specialties',
      title: 'Specialties',
      type: 'array',
      of: [{type: 'string'}],
      group: 'content',
      options: {layout: 'tags'},
    }),
    defineField({
      name: 'languages',
      title: 'Languages',
      type: 'array',
      of: [{type: 'string'}],
      group: 'content',
      options: {layout: 'tags'},
    }),
    defineField({
      name: 'locations',
      title: 'Locations',
      type: 'array',
      of: [{type: 'reference', to: [{type: 'location'}]}],
      group: 'content',
    }),
    defineField({
      name: 'acceptingNewPatients',
      title: 'Accepting new patients',
      type: 'boolean',
      group: 'content',
      initialValue: false,
    }),
    defineField({
      name: 'showOnTeamPage',
      title: 'Show on team page',
      type: 'boolean',
      group: 'settings',
      initialValue: true,
    }),
    defineField({
      name: 'sortOrder',
      title: 'Sort order',
      type: 'number',
      group: 'settings',
      description: 'Lower numbers appear first.',
      validation: (rule) => rule.integer().min(0),
    }),
    defineField({
      name: 'seo',
      title: 'SEO',
      type: 'seoFields',
      group: 'settings',
    }),
  ],
  orderings: [
    {
      title: 'Sort order, name',
      name: 'sortOrderAsc',
      by: [
        {field: 'sortOrder', direction: 'asc'},
        {field: 'lastName', direction: 'asc'},
        {field: 'firstName', direction: 'asc'},
      ],
    },
  ],
  preview: {
    select: {
      title: 'name',
      subtitle: 'role',
      media: 'image',
    },
  },
})
