import {DocumentTextIcon} from '@sanity/icons'
import {defineField, defineType} from 'sanity'

export const websiteManagedPages = [
  {
    id: 'website-page-care',
    key: 'care',
    path: '/care',
    group: 'care',
    title: 'Care overview',
    pageTitle: 'Integrated care, all in one place.',
    eyebrow: 'Care',
    description:
      'We bring primary care, addiction medicine, recovery support, and wellness care together so your team already knows your history — no retelling required.',
  },
  {
    id: 'website-page-contact',
    key: 'contact',
    path: '/contact',
    group: 'patientAccess',
    title: 'Contact',
    pageTitle: 'Contact Rise Up',
    eyebrow: 'Contact',
    description:
      'Reach Rise Up for non-urgent questions, referrals, access support, and general information.',
  },
  {
    id: 'website-page-referrals',
    key: 'referrals',
    path: '/referrals',
    group: 'patientAccess',
    title: 'Referrals',
    pageTitle: 'Refer a patient to Rise Up',
    eyebrow: 'Referrals',
    description:
      'Referral partners can connect patients with integrated treatment, recovery, and primary care services.',
  },
  {
    id: 'website-page-careers',
    key: 'careers',
    path: '/careers',
    group: 'organization',
    title: 'Careers',
    pageTitle: 'Work with Rise Up',
    eyebrow: 'Careers',
    description: 'Explore opportunities to join a team focused on integrated, community-rooted care.',
  },
  {
    id: 'website-page-insurance-payment',
    key: 'insurance-payment',
    path: '/insurance-payment',
    group: 'patientAccess',
    title: 'Insurance and payment',
    pageTitle: 'Insurance and payment information',
    eyebrow: 'Insurance and payment',
    description: 'Find general insurance and payment information before starting care with Rise Up.',
  },
  {
    id: 'website-page-patient-resources',
    key: 'patient-resources',
    path: '/patient-resources',
    group: 'patientAccess',
    title: 'Patient resources',
    pageTitle: 'Patient resources',
    eyebrow: 'Patient resources',
    description:
      'Helpful links and guidance for patients navigating care, appointments, and support resources.',
  },
  {
    id: 'website-page-addiction-medicine',
    key: 'addiction-medicine',
    path: '/care/addiction-medicine',
    group: 'care',
    title: 'Addiction medicine',
    pageTitle: 'Addiction medicine at Rise Up',
    eyebrow: 'Addiction medicine',
    description: 'Evidence-based addiction medicine integrated with primary care and recovery support.',
  },
  {
    id: 'website-page-primary-care',
    key: 'primary-care',
    path: '/care/primary-care',
    group: 'care',
    title: 'Primary care',
    pageTitle: 'Primary care connected to the whole picture',
    eyebrow: 'Primary care',
    description: 'Primary care at Rise Up is coordinated with recovery support and ongoing wellness needs.',
  },
  {
    id: 'website-page-services',
    key: 'services',
    path: '/care/services',
    group: 'care',
    title: 'Services',
    pageTitle: 'Care that works together',
    eyebrow: 'Services',
    description: 'Explore integrated primary care, recovery services, and wellness support from Rise Up.',
  },
  {
    id: 'website-page-programs',
    key: 'programs',
    path: '/care/programs',
    group: 'care',
    title: 'Programs',
    pageTitle: 'Programs built around real needs',
    eyebrow: 'Programs',
    description:
      'Learn about Rise Up programs designed to support recovery, wellness, and long-term stability.',
  },
  {
    id: 'website-page-weight-loss-mgmt',
    key: 'weight-loss-mgmt',
    path: '/care/weight-loss-mgmt',
    group: 'care',
    title: 'Weight loss management',
    pageTitle: 'Weight loss management',
    eyebrow: 'Weight loss',
    description: 'Medical support for weight loss goals, metabolic health, and long-term wellness.',
  },
  {
    id: 'website-page-new-patients',
    key: 'new-patients',
    path: '/new-patients',
    group: 'patientAccess',
    title: 'New patients',
    pageTitle: 'Starting care is simpler than it sounds',
    eyebrow: 'New patients',
    description:
      "Whether you're coming in for primary care, weight loss management, or addiction medicine — we'll walk you through every step.",
  },
  {
    id: 'website-page-about',
    key: 'about',
    path: '/about',
    group: 'organization',
    title: 'About',
    pageTitle: 'Whole-person care, rooted in community',
    eyebrow: 'About us',
    description:
      'RiseUp Health & Wellness brings primary care, addiction medicine, recovery support, and wellness care together under one roof — so patients get coordinated support.',
  },
  {
    id: 'website-page-team',
    key: 'team',
    path: '/team',
    group: 'organization',
    title: 'Team',
    pageTitle: 'Our Team',
    eyebrow: 'People',
    description: 'Clinicians and staff committed to integrated, compassionate care.',
  },
  {
    id: 'website-page-locations',
    key: 'locations',
    path: '/locations',
    group: 'organization',
    title: 'Locations',
    pageTitle: 'Our Locations',
    eyebrow: 'Where to find us',
    description: 'We serve patients across West Virginia from convenient community locations.',
  },
] as const

export const websitePageKeys = [
  {title: 'Homepage', value: 'home'},
  ...websiteManagedPages.map((page) => ({
    title: page.title,
    value: page.key,
  })),
  {title: 'Privacy policy', value: 'privacy-policy'},
  {title: 'Terms of service', value: 'terms-of-service'},
] as const

export const websitePage = defineType({
  name: 'websitePage',
  title: 'Website page',
  type: 'document',
  icon: DocumentTextIcon,
  groups: [
    {name: 'page', title: 'Page', default: true},
    {name: 'homepage', title: 'Homepage'},
    {name: 'blocks', title: 'Blocks'},
    {name: 'pageSpecific', title: 'Page-specific'},
    {name: 'legal', title: 'Legal'},
    {name: 'seo', title: 'SEO'},
    {name: 'system', title: 'System'},
  ],
  fields: [
    defineField({
      name: 'key',
      title: 'Page key',
      type: 'string',
      description: 'Stable internal key used by the website to load this page.',
      group: 'system',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'path',
      title: 'Canonical path',
      type: 'string',
      description: 'Public URL path, such as /care/services.',
      group: 'system',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'pageType',
      title: 'Page type',
      type: 'string',
      group: 'system',
      options: {
        list: [
          {title: 'Homepage', value: 'home'},
          {title: 'Landing page', value: 'landing'},
          {title: 'Custom page', value: 'custom'},
          {title: 'Legal page', value: 'legal'},
        ],
      },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'status',
      title: 'Status',
      type: 'string',
      group: 'system',
      options: {
        layout: 'radio',
        list: [
          {title: 'Published', value: 'published'},
          {title: 'Draft', value: 'draft'},
        ],
      },
      initialValue: 'published',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'title',
      title: 'Page title',
      type: 'string',
      group: 'page',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'eyebrow',
      title: 'Eyebrow',
      type: 'string',
      group: 'page',
      hidden: ({document}) => document?.pageType === 'home' || document?.pageType === 'legal',
    }),
    defineField({
      name: 'description',
      title: 'Description',
      type: 'text',
      rows: 3,
      group: 'page',
      hidden: ({document}) => document?.pageType === 'home' || document?.pageType === 'legal',
    }),
    defineField({
      name: 'hero',
      title: 'Hero',
      type: 'homepageHero',
      group: 'homepage',
      hidden: ({document}) => document?.pageType !== 'home',
    }),
    defineField({
      name: 'heroFeaturePanel',
      title: 'Hero feature panel',
      type: 'homepageFeaturePanel',
      group: 'homepage',
      hidden: ({document}) => document?.pageType !== 'home',
    }),
    defineField({
      name: 'careModelHighlights',
      title: 'Care model highlights',
      type: 'array',
      of: [{type: 'string'}],
      group: 'homepage',
      hidden: ({document}) => document?.pageType !== 'home',
    }),
    defineField({
      name: 'serviceHighlights',
      title: 'Care option cards',
      type: 'array',
      of: [{type: 'serviceHighlight'}],
      group: 'homepage',
      hidden: ({document}) => document?.pageType !== 'home',
    }),
    defineField({
      name: 'careOptions',
      title: 'Care options intro',
      type: 'homepageCareOptions',
      group: 'homepage',
      hidden: ({document}) => document?.pageType !== 'home',
    }),
    defineField({
      name: 'referralCta',
      title: 'Referral CTA',
      type: 'ctaBlock',
      group: 'homepage',
      hidden: ({document}) => document?.pageType !== 'home',
    }),
    defineField({
      name: 'blocks',
      title: 'Page blocks',
      type: 'array',
      group: 'blocks',
      hidden: ({document}) => document?.pageType === 'home' || document?.pageType === 'legal',
      of: [
        {type: 'pageSection'},
        {type: 'ctaBlock'},
        {type: 'careModelBlock'},
        {type: 'conditionsBlock'},
        {type: 'faqBlock'},
        {type: 'servicesBlock'},
        {type: 'programsBlock'},
      ],
    }),
    defineField({
      name: 'contactForm',
      title: 'Contact form copy',
      type: 'contactFormContent',
      group: 'pageSpecific',
      hidden: ({document}) => document?.key !== 'contact',
    }),
    defineField({
      name: 'newPatientSteps',
      title: 'New patient steps',
      type: 'array',
      group: 'pageSpecific',
      of: [{type: 'newPatientStep'}],
      hidden: ({document}) => document?.key !== 'new-patients',
    }),
    defineField({
      name: 'newPatientAccessCards',
      title: 'New patient access cards',
      type: 'array',
      group: 'pageSpecific',
      of: [{type: 'newPatientAccessCard'}],
      hidden: ({document}) => document?.key !== 'new-patients',
    }),
    defineField({
      name: 'emptyStateText',
      title: 'Empty state text',
      type: 'string',
      description: 'Shown only on pages that list documents, such as Team or Locations.',
      group: 'pageSpecific',
      hidden: ({document}) => !['team', 'locations'].includes(String(document?.key ?? '')),
    }),
    defineField({
      name: 'referralPdf',
      title: 'Referral PDF',
      type: 'file',
      description: 'Upload the printable referral form shown as a download button on the referrals page.',
      options: {
        accept: 'application/pdf',
      },
      group: 'pageSpecific',
      hidden: ({document}) => document?.key !== 'referrals',
    }),
    defineField({
      name: 'downloadLabel',
      title: 'Download button label',
      type: 'string',
      group: 'pageSpecific',
      hidden: ({document}) => document?.key !== 'referrals',
    }),
    defineField({
      name: 'missingPdfMessage',
      title: 'Missing PDF message',
      type: 'string',
      group: 'pageSpecific',
      hidden: ({document}) => document?.key !== 'referrals',
    }),
    defineField({
      name: 'pdfSectionHeading',
      title: 'PDF section heading',
      type: 'string',
      group: 'pageSpecific',
      hidden: ({document}) => document?.key !== 'referrals',
    }),
    defineField({
      name: 'pdfSectionDescription',
      title: 'PDF section description',
      type: 'text',
      rows: 3,
      group: 'pageSpecific',
      hidden: ({document}) => document?.key !== 'referrals',
    }),
    defineField({
      name: 'formEyebrow',
      title: 'Form eyebrow',
      type: 'string',
      group: 'pageSpecific',
      hidden: ({document}) => document?.key !== 'referrals',
    }),
    defineField({
      name: 'formHeading',
      title: 'Form heading',
      type: 'string',
      group: 'pageSpecific',
      hidden: ({document}) => document?.key !== 'referrals',
    }),
    defineField({
      name: 'formDescription',
      title: 'Form description',
      type: 'text',
      rows: 3,
      group: 'pageSpecific',
      hidden: ({document}) => document?.key !== 'referrals',
    }),
    defineField({
      name: 'formDocumentNote',
      title: 'Form document note',
      type: 'text',
      rows: 3,
      group: 'pageSpecific',
      hidden: ({document}) => document?.key !== 'referrals',
    }),
    defineField({
      name: 'formConsentLabel',
      title: 'Consent checkbox label',
      type: 'text',
      rows: 3,
      group: 'pageSpecific',
      hidden: ({document}) => document?.key !== 'referrals',
    }),
    defineField({
      name: 'body',
      title: 'Legal body',
      type: 'array',
      group: 'legal',
      hidden: ({document}) => document?.pageType !== 'legal',
      of: [
        {
          type: 'block',
          styles: [
            {title: 'Normal', value: 'normal'},
            {title: 'Heading', value: 'h2'},
            {title: 'Sub-heading', value: 'h3'},
          ],
          lists: [
            {title: 'Bullet', value: 'bullet'},
            {title: 'Numbered', value: 'number'},
          ],
          marks: {
            decorators: [
              {title: 'Strong', value: 'strong'},
              {title: 'Emphasis', value: 'em'},
            ],
            annotations: [],
          },
        },
      ],
    }),
    defineField({
      name: 'seo',
      title: 'SEO',
      type: 'seoFields',
      group: 'seo',
    }),
  ],
  preview: {
    select: {
      title: 'title',
      path: 'path',
      pageType: 'pageType',
    },
    prepare: ({title, path, pageType}) => ({
      title,
      subtitle: `${path ?? 'No path'} · ${pageType ?? 'page'}`,
    }),
  },
})
